---
title: "Teste para apresentação"
subtitle: "Preparando a dissertação"
author: "Diego dos Santos Fernandes"
institute: "Instituto Brasiliense de Direito Público - IDP"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    
---


```{r setup, include=FALSE}

library(jsonlite)
library (tidyverse)
library(pacman)
library(httr)
library(rjstat)
library(glue)
library(countrycode)
library(data.table)
library(yaml)
library(xaringanthemer)

```

---

# 1. Introdução


- **Objetivo**: Avaliar a mudança dos critérios de analises de atos de concentração (Lei 12.529/2011) nas fusões e aquisições internacionais no Brasil.Principalmente ex-post para ex-ante
- **Hipótese**: Análise de atos de concentração ex-post criaria uma insegurança jurídica, principalmente para as empresas internacionais.
- **Metodologia**: *Synthetic Control Method*  
- **Resultado**: De acordo com método utilizado, houve impacto estimado no número de fusões e aquisições em 742 operações realizadas.

---

# 2. Revisão da Literatura

- Defesa da Concorrência e análise de atos de concentração
- Método de controle Sintético

---
# 2.1 Defesa da Concorrência e análise de atos de concentração
 - Em menos de 20 anos o Brasil alterou o marco que regulava a defesa da concorrência: Lei nº 8.884/1994 e a Lei 12.529/2011
 - Lei nº 8.884/1994: alterações importantes
     - Dentro do Contexto das Reformas regulatórias da década de noventa
     - Transformou o Cade em Autarquia
     - Mas apresentava um controle *ex-post* de Atos de Concentração.
     - Este tipo de análise geraria uma insegurança jurídica
     
     
---

#2.1 Defesa da Concorrência e análise de atos de concentração

- Lei 12.529/11
     - Intenção de cobrir lacunas e inserir inovações na legislação antitruste
    - Centralização de algumas atribuições ao Cade: "SuperCade"
    - Inovações processuais
    - Instituiu a análise prévia de atos de Concentração
    
---

# 2.2 Método de Controle Sintético 
- Synthetic Control Method (SCM)
- Abadie e Gardeazabal (2003) e Abadie *et al.* (2010)
- Estimar os efeitos causais de intervenções
- **Uma combinação de unidades não afetadas geralmente fornece comparação mais apropriada** 
- Unidades Agregadas
- Uma unidade de Tratamento
- Análise comparativa
- Aplicação em Ciências Política, Economia e Saúde
- Aplicação em Avaliação de Políticas Públicas


---

# 2.2 SCM - Apresentação do Modelo

 - Amostra
    - $(J+1)$ unidades
    - $(j=1)$ a unidade de tratamento
 - Unidade Temporal
    - $t=1,…T$
    - $T_0$ é o último período pré-intervenção
    - $(1<T_{0~}<T)$
    
---
 # 2.2 Apresentação do Modelo

  - $\mathbf{Y}$ é a variável de interesse - F&A internacionais
  - $\mathbf{Y_{1t}^{I}}$ a unidade $j = 1$  no tempo  $t$  que sofreu a intervenção
  - $\mathbf{Y_{1t}^{N}}$ a unidade de tratamento cado não sofresse a intervenção
  - $\mathbf{Y_{jt}^{N}}$ as unidades que não sofreram a intervenção
 O efeito da intervenção no período t é dado por: 
$$\tau_{1t}=Y_{1t}^{I}- Y_{1t}^{N}$$
 
---
# 2.2 Apresentação do Modelo
<style>
body {
text-align: justify}
</style>

O método controle sintético forma uma unidade sintética através de uma combinação convexa de todo as unidades de comparação definida pelo vetor $W=~ \left( w_{2}, \ldots , w_{j+1} \right) ^{'}$, sendo $0 \leq w_{j} \leq 1$. Portanto:

 
    
$$\mathbf{\hat{Y}_{1t}^{N}}=  \sum _{j=2}^{J+1}w_{j}Y_{jt}^{N}$$
Com isso também encontramos $\hat{ \tau}_{1t}$
$$\hat{ \tau}_{1t}=~ Y_{1t}^{I}- \hat{Y}_{1t}^{N}$$

--- 
---
# 2.2 Apresentação do Modelo
Assim, Seja  $X_{1}$ um vetor de dimensão  $\left( k \times 1 \right)$  contanto as caraterísticas da unidade de tratamento e  $X_{0}~$ como uma uma matriz  $k~\mathrm{ \times  J}$  contendo os valores da mesma variável dentre aos candidatos à unidade sintéticas (donor pool). Assim, encontra-se $W^{\ast} \textbf{ }$como o valor de  $W$ que minimiza a expressão:

$$\min_w \quad\Vert X_{1}-X_{0}W \Vert V= \sqrt[]{ \left( X_{1}-X_{0}W \right) ^{'}V \left( X_{1}-X_{0}W \right)}$$
$V_{k\mathrm{ \times }k}$ matriz simétrica semidefinida que tem função de atribuir os pesos em cada variável. 
$$\mathbf{V^{*}} = \Vert Y_{1}^{P}-Y_{0}^{P}\mathbf{W^{*}}(V) \Vert$$
---
# 3. Metodologia

 1. Orientado a dados
 2. Uma vez definido a variável de interesse e a unidade de tratamento:
     - Delimitação do *donor pool* e das variáveis
     - Base de dados
     - Apresentação dos Resultados e testes.
     
---

## 3.2 Base de dados - *escopo temporal*

- Delimitação do Tempo
    - Dados de 2000 a 2018
-  Data da Intervenção
     - A Lei 12.529/2011 com efeitos em 2012
     - O ano 2011 escolhido como intervenção

---

## 3.2 Base de dados - *Donor pool*

- *Donor pool*: países dos BRICS, México e os países da América do Sul
    - **Exceção**: Venezuela e Índia
    - *Venezuela*: confiabilidade dos dados
    - *Índia*: regulamentação similar em 2011
    
--- 

## 3.2 Base de dados - *Variáveis*   

1. **World Delevopment Indicator (WDI)** 
   - *GDP per capita (constant 2010 US$)* 
   - *GDP growth (annual %)*
   - *Foreign direct investment, net inflows (% of GDP)*
   - *GDP per capita growth (annual %), Final consumption expenditure (annual % growth)*
2. **Heritage Foundation**
 - *Index of Economic Freedom*


---
---
#Resultados

- Peso de cada País na Unidade Sintética

$$\begin{table}
\caption{Peso W na Unidade Sintétitica} 
\begin{tabular}{l | c |}
Country & W.weigth \\
\hline \hline
Argentina & 0.3---5 \\ 
Mexico & 0.28 \\
Russian Federation & 0.25 \\
Chile & 0.11 \\
Uruguay & 0.00 \\
South Africa & 0.00 \\
China & 0.00 \\
Colombia & 0.00 \\
Peru & 0.00 \\
Bolivia & 0.00 \\
Paraguay & 0.00 \\
\end{tabular}
\end{table}$$
---

