---
title: "Tratamento dos dados"
author: "Diego dos Santos Fernandes"
date: "31/05/2020"
output:
  pdf_document: default
  html_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(wbstats)
library(StandardizeText)
library(httr)
library(jsonlite)
library(rjstat)
```

```{r}
# limpando os dados da UNCTAD
# importanto os dados

library(readxl)
WIR19_tab07 <- read_excel("WIR19_tab07.xlsx", 
    skip = 2)
MA <- WIR19_tab07



```
 
```{r}
# faxinando os dados


MA <- MA %>% 
  na.omit() %>% 
   pivot_longer(-`Region/economy`, names_to = "Ano", values_to = "number") 

MA <- MA %>% 
  clean_names() %>% 
  mutate(ano = as.numeric(ano))



```




```{r}

tudo <- read_csv("tudo.csv")

tudo$Country <- gsub( "Venezuela, RB", "Venezuela", tudo$Country)

completo <- right_join(MA, tudo, by = c("ano" = "Year", "region_economy" = "Country"))


```


```{r}

brasil <- completo %>% 
  filter(region_economy == "Brazil", ano %in% c(1995:2018))
```

```{r}
sel <- completo %>% 
  filter(region_economy %in% c("Brazil","Argentina","Bolivia", "Chile", "Colombia", "Paraguay","Peru", "Uruguay", "China","India", "Russian Federation", "South Africa", "Mexico"),
         ano %in% c(2000:2018) ) %>% 
  select(region_economy,ano,number,`GDP per capita (constant 2010 US$)`,`GDP growth (annual %)`,`Foreign direct investment, net inflows (% of GDP)`,`GDP per capita growth (annual %)`,`Foreign direct investment, net outflows (% of GDP)`,`Final consumption expenditure (annual % growth)`,`Gross fixed capital formation, private sector (% of GDP)`)



gdp <- sel %>% 
  select(region_economy, ano,`GDP per capita (constant 2010 US$)`) %>% 
  mutate(log_gdp = log(`GDP per capita (constant 2010 US$)`) )


```



```{r}
#juntando com os dados de economic fredom
ef <- read_csv("ef.csv") %>% 
  rename(index_ef = `Overall Score`)

ef$Name <- gsub( "Russia", "Russian Federation", ef$Name)


index <- ef %>% 
  select(Name,`Index Year`, index_ef)

rodar <- left_join(sel, index, by = c("ano" = "Index Year", "region_economy" = "Name"))



```

```{r}
#adicionando manufatura
manufatura <- rjstat::fromJSONstat("http://api.worldbank.org/v2/country/all/indicator/NV.IND.MANF.ZS?format=jsonstat")

manufatura <- manufatura[["WDI data; total 15840 records."]]  

manufatura <- manufatura %>% pivot_wider(names_from = Series, values_from = value) %>% 
  mutate(Year = as.numeric(Year))

#adicionando inflação

inflacao <- rjstat::fromJSONstat("http://api.worldbank.org/v2/country/all/indicator/FP.CPI.TOTL.ZG?format=jsonstat")

inflacao <- inflacao[["WDI data; total 15840 records."]]  

inflacao <- inflacao %>% pivot_wider(names_from = Series, values_from = value) %>% 
  mutate(Year = as.numeric(Year))



rodar <- left_join(rodar, manufatura, by = c("ano" = "Year", "region_economy" = "Country"))
rodar <- left_join(rodar, inflacao, by = c("ano" = "Year", "region_economy" = "Country"))
write_csv(rodar, "rodar.csv")

```
 
 
 
 
```{r}
# grafico do Brasil
ggthemr("greyscale")
brasil <- MA %>% 
  filter(`Region/economy` == "Brazil", Ano %in% c(2008:2018)) %>% 
  mutate(Ano = as_factor(Ano)) %>% 
  ggplot(aes(x = Ano, y = number, group = 1))+
  geom_col()
  
  
  
brasil


```
 
 
 